### ISSUE TITLE
Can't start LOTT revamped

### ISSUE THREAD

**Issue by lightonflux** [Amaz1/Lord-of-the-Test#15]
Here the debug log:

        17:16:10: ERROR[main]: ========== ERROR FROM LUA ===========
        17:16:10: ERROR[main]: Failed to load and run script from 
        17:16:10: ERROR[main]: /home/moritz/.minetest-dev/bin/../games/Lord-of-the-Test/mods/Arda/kelvar/init.lua:
        17:16:10: ERROR[main]: cannot open /home/moritz/.minetest-dev/bin/../games/Lord-of-the-Test/mods/Arda/kelvar/guards/npcf/npcf.lua: Datei oder Verzeichnis nicht gefunden
        17:16:10: ERROR[main]: stack traceback:
        17:16:10: ERROR[main]:  [C]: in function 'dofile'
        17:16:10: ERROR[main]:  .../bin/../games/Lord-of-the-Test/mods/Arda/kelvar/init.lua:1: in main chunk
        17:16:10: ERROR[main]: ======= END OF ERROR FROM LUA ========
        17:16:10: ERROR[main]: Server: Failed to load and run /home/moritz/.minetest-dev/bin/../games/Lord-of-the-Test/mods/Arda/kelvar/init.lua
        17:16:10: ERROR[main]: ModError: ModError: Failed to load and run /home/moritz/.minetest-dev/bin/../games/Lord-of-the-Test/mods/Arda/kelvar/init.lua

**Comment by fishyWET** [comment]
Do not download the latest version, i was working on something but haven't got the time to finish it, so it is currently unfinished and doesn't work. Download the latest playable version from https://github.com/Amaz1/Lord-of-the-Test/releases
